### ISSUE TITLE
Cache packages and bower

### ISSUE THREAD

**Issue by matheusbrat** [REscour/heroku-buildpack-nodejs-gulp-bower-sass#2]
Hello,

If I record correctly the packages.json packages are cached right? Is it possible to cache bower packages as well? 

I'm using this buildpack but it is taking so long to deploy a version. 

Any ideas on what I could optimize to get a faster deploy?

**Comment by akasper** [comment]
@x-warrior You can cache those files by modifying `bin/compile` to do so. I dare not offer further support than that, lest I inadvertently nuke your entire project with my cargo cult understanding of the inner workings of Heroku buildpacks. 

Please bear in mind that this is our highly-hacked, just-trying-to-get-it-to-work-for-one-strange-edgecase-we're-dealing-with version of this buildpack. I believe this is a fork of @davidmfoley's less specific version of the buildpack, available here: https://github.com/davidmfoley/heroku-buildpack-nodejs-gulp-bower

**Comment by akasper** [comment]
Pardon me. This is a fork of @evenemento's buildpack of the same name.

**Comment by davidmfoley** [comment]
My fork was also a "need to hack this thing right now" job. The original repo is https://github.com/heroku/heroku-buildpack-nodejs

**Comment by matheusbrat** [comment]
@akasper 

Thanks for the reply and for the tip.

I was trying to get gulp + bower + sass to work with heroku and your buildpack (and probably @davidmfoley) were the only ones that worked for this task.
